<!DOCTYPE html>
<html>
    <head>

        <title>Heroes Profile | Opt Out </title>
        <meta name="robots" content="noindex">


    </head>
    <body>


        <div class="main-content opt-out">

          <div class="player-name">
            <h2>Opt Out</h2>
          </div>
            <div class="standard-page-content">
<section>

<p>All of the data on this site is dynamically generated by Blizzard data obtained by replays uploaded to HotsAPI. Please refer to Blizzard's licensing agreement regarding their ownership of your battletag/blizz_id.  Any players' replay they upload may have information on your assigned battletag and we do not control which data is uploaded to HotsAPI.</p>
<p>If you do not wish for your battletag to appear on this site on Profile or Match pages, we provide the option for you to opt-out. In order to do this, we require that you authenticate with your Blizzard account. This ensures that you are the player with that blizz_id and ensures that the system is not abused by those wishing to remove other players' data.</p>
<p>Please choose a region below and click "opt-out". You will be redirected to Blizzard's secure authentication and asked to allow access for your Blizz ID and Battletag. This is the only information we use, and we do not store this information anywhere. We do not collect or store any personal information. After you have opted out, you may remove your authorization for this website by going to your Battle.net account under "Security & Privacy" and managing your authorized applications.</p>
<p>Once you have opted-out, data uploaded from replays in which you played a game will still be used to calculate data across the site, but your Battletag and Profile page will be removed.</p>


<form action="optout/login" id="optout">
  <select name="region" required><option value="">Please Choose a Region</option>
    <option value="US">US</option>
    <option value="EU">EU</option>
    <option value="KR">KR</option>
    <option value="TW">TW</option>
    <option value="SEA">SEA</option>
      </select>
      <input type="submit" value="Opt Out"/>
</form>
</section>
</div>
</div>
</body>
</html>
